name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          # mdbook-version: '0.3.7'
          mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
        
        # GH_TOKEN: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
        # Interesting note: The GITHUB_TOKEN secret has the deployments scope
        # w/ read/write access for repositories.
        # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token
        # for more info.
        # Note: This will be commented until support for automatically building
        # the deployed results (a la GitHub Pages + Jekyll) arrives.
        # See https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/26869
        # for more info.